### ISSUE TITLE
Germplasm Map 500 Server Error

### ISSUE THREAD

**Issue by StevenCannon-USDA** [legumeinfo/grinconnect#2]
https://peanutbase.org/germplasm/map gives  
Error: 500 Internal Server Error /germplasm/map/search?v=1567529907214 <h1>Server Error (500)</h1>

**Comment by adf-ncgr** [comment]
fixed by applying the postgis upgrade that had previously been done on legumeinfo (forgot that pb had its own instance of this and would be similarly affected.
